# Generated by Django 5.2.10 on 2026-01-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('mongo_db_name', models.CharField(max_length=100)),
                ('mysql_db_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='MongoServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uri', models.TextField()),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mongo_servers',
            },
        ),
        migrations.CreateModel(
            name='MySQLServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No disponible')], default='DISPONIBLE', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mysql_servers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default='db52c278e1b2487d85d5722e12c76c6c', max_length=64, unique=True)),
                ('is_general', models.BooleanField(default=False, help_text='Invitación general reutilizable')),
                ('email', models.EmailField(blank=True, help_text='Email destino si es invitación específica', max_length=254, null=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Si requiere aprobación del Dueño (OWNER)')),
                ('is_used', models.BooleanField(default=False, help_text='Marca si ya fue utilizada (solo para específicas)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.company')),
            ],
            options={
                'db_table': 'company_invitations',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='mongo_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mongoserver'),
        ),
        migrations.AddField(
            model_name='company',
            name='mysql_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mysqlserver'),
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'user_company',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
