# Generated by Django 5.2.10 on 2026-01-29 06:14

import core.db.sqlite.models.company_invitation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvitation',
            name='token',
            field=models.CharField(db_index=True, default=core.db.sqlite.models.company_invitation.generate_token, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companyinvitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'company_join_requests',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
