# Generated by Django 5.2.10 on 2026-01-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companyinvitation_token_companyjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
