# Generated by Django 5.2.10 on 2026-01-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_activation_code_user_activation_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agente_retencion',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='contribuyente',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='obligado',
            field=models.CharField(default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='regimen',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
