# Generated by Django 5.2.10 on 2026-01-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_agente_retencion_company_contribuyente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='role_in_erp',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
