# Generated by Django 5.2.10 on 2026-01-31 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usercompany_role_in_erp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompany',
            old_name='role_in_erp',
            new_name='role_slug',
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='core.user')),
            ],
            options={
                'db_table': 'password_reset_token',
                'indexes': [models.Index(fields=['token'], name='password_re_token_d8eb05_idx'), models.Index(fields=['expires_at'], name='password_re_expires_214fae_idx')],
            },
        ),
    ]
