# Generated by Django 5.2.10 on 2026-02-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_role_in_erp_usercompany_role_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mysql_db_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='mysql_db_user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='mysql_db_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
