# Generated by Django 5.2.10 on 2026-02-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_mysql_db_password_company_mysql_db_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
